export const REQUEST_REQUEST = 'REQUEST_REQUEST'
export const FAILURE_REQUEST = 'FAILURE_REQUEST'
export const SUCCESS_REQUEST = 'SUCCESS_REQUEST'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'

export const FETCH_REPORTS = 'FETCH_REPORTS'
export const ADD_REPORT = 'ADD_REPORT'
export const UPDATE_REPORT = 'UPDATE_REPORT'
export const REMOVE_REPORT = 'REMOVE_REPORT'
